### ISSUE TITLE
Twitter Block Plugin Not able to edit settings as Journal Manger only as Admin

### ISSUE THREAD

**Issue by RBoelter** [RBoelter/twitterBlock#9]
From PKP Forum: https://forum.pkp.sfu.ca/t/twitter-block-plugin-not-able-to-edit-settings-as-journal-manger-only-as-admin/69953

### Description of issue or problem I’m having:
I have installed the Twitter Block Plugin for one of our Journals to work with. The user outside of our immediate office can only have Journal Manger as the highest level user. The user cannot see the plugin in the Installed Plugin only in the Plugin Gallery. They need to be able to set up the settings for the plugin to work. Is this normal behavior that only Admin level can edit the settings and see it in the Installed Plugin area?

Application Version - e.g., OJS 3.1.2: We have 3.3.0.5 installed.

The Plugin was installed using the Plugin Gallery and it says it is up to date. It says it is v3.2.0.1.

**Comment by ThomasLecocq** [comment]
Same behaviour observed on OJS 3.2.1.1:

v 3.2.0.1 mentionned in Plugin Gallery (up to date) doesn't appear in the Installed Plugins:
![image](https://user-images.githubusercontent.com/916937/146389757-132897eb-148c-4c96-8403-17cf82a1f019.png)

**Comment by ThomasLecocq** [comment]
solution in the meantime: 

- go to https://publish.twitter.com/
- generate the embed code
- in OJS:
  - enable "custom header" plugin and add the ``<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`` content in the footer
  - enable the "custom blocks manager", create a new block called twitter and paste the embed code in <> source code mode
  - in the website settings - appearance - setup -> enable the twitter block

**Comment by amandastevens** [comment]
What version of the plugin has this change been made in (allowing journal managers to access plugin configuration settings)?  I see the issue is closed but it has no milestone.

**Comment by gonzalognzl** [comment]
Hi @RBoelter,  using OJS 3.3.0.x and Twitter block plugin 3.2.0.1 this issue persists.
